gurmukhischool/urls.py
from django.contrib import admin
from django.urls import path, include
from portal.views import activate, account_activation_sent
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('school/', include('pages.urls')),
    path('', include('main.urls')),
    path('portal/', include('portal.urls')),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('account_activation_sent/', account_activation_sent, name='account_activation_sent'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexMain, name='indexMain'),
    # path('events', views.eventsMain, name='eventsMain'),
    path('about', views.aboutMain, name='aboutMain'),
    path('contact', views.contact, name='contact'),
    path('sitemap', views.sitemap, name='sitemap'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('subscribe/submit', views.subscribePOST, name='subscribePOST'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('students/<int:course_id>', views.students, name='students'),
    path('students/remove/<int:course_id>', views.removeStudentFromCourse, name='removeStudentFromCourse'),
    path('', views.courses, name='courses'),
    path('admin/', views.adminViewHome, name = 'adminViewHome'),
    path('admit/user/waitlist', views.admit_user, name='admit_user'),
    path('admin/carousel', views.carousel_management, name = 'carousel_management'),
    path('admin/carousel/school/upload', views.gurmukhiSchoolImageUpload, name = 'gurmukhiSchoolImageUpload'),
    path('admin/carousel/upload', views.mainCarouselImageUpload, name = 'mainCarouselImageUpload'),
    path('email/delete/<int:email_id>/', views.delete_email, name='delete_email'),
    path('admin/users', views.adminUsers, name = 'adminUsers'),
    path('admin/kirtan/add', views.addKirtan, name = 'addKirtan'),
    path('admin/users/edit', views.changeUserInfo, name = 'changeUserInfo'),
    path('admin/contact', views.adminContactView, name = 'adminContactView'),
    path('courses/syllabus/add/<int:course_id>', views.upload_syllabus, name = 'upload_syllabus'),
    path('courses/syllabus/view/<int:course_id>', views.view_syllabus, name = 'view_syllabus'),
    path('courses/add', views.courseAdd, name='courseAdd'),
    path('courses/<int:course_id>', views.course, name='course'),
    path('courses/delete/<int:course_id>', views.deleteCourse, name='deleteCourse'),
    path('section/<int:course_id>/add', views.sectionAdd, name='sectionAdd'),
    path('section/<int:section_id>/folder/view/<int:folder_id>', views.folder, name='folder'),
    path('section/<int:section_id>/folder/file/upload/<int:folder_id>', views.uploadFile, name='uploadFile'),
    path('folder/add', views.folderAdd, name='folderAdd'),
    path('section/<int:section_id>/order/up', views.moveSectionUp, name = "moveSectionUp"),
    path('section/<int:section_id>/delete', views.deleteSection, name = "deleteSection"),
    path('section/<int:section_id>/order/down', views.moveSectionDown, name = "moveSectionDown"),
    path('section/<int:section_id>/visibility', views.changeVisibility, name = "changeVisibility"),
    path('section/<int:section_id>/folder/assignment/create/<int:folder_id>', views.createAssignment, name='createAssignment'),
    path('section/<int:section_id>/folder/assignment/view/<int:folder_id>/<int:assignment_id>', views.viewAssignment, name='viewAssignment'),
    path('section/<int:section_id>/folder/assignment/edit/<int:folder_id>/<int:assignment_id>', views.editAssignment, name='editAssignment'),
    path('section/<int:section_id>/folder/assignment/edit/<int:folder_id>/<int:assignment_id>', views.editAssignment, name='editAssignment'),
    path('submission/<int:folder_id>/folder/<int:user_id>/assignment/<int:assignment_id>', views.submissions, name='submissions'),
    path('grade/submission/<int:folder_id>/folder/<int:user_id>/assignment/<int:assignment_id>/<int:course_id>', views.assignGradeToAssignment, name='assignGradeToAssignment'),
    path('section/<int:section_id>/folder/assignment/delete/<int:folder_id>/<int:assignment_id>', views.deleteAssignment, name='deleteAssignment'),
    path('section/<int:section_id>/folder/assignment/delete/<int:folder_id>/<int:assignment_id>', views.deleteAssignment, name='deleteAssignment'),
    path('section/<int:section_id>/folder/assignment/submit/<int:folder_id>/<int:assignment_id>/delete', views.deleteSubmission, name='deleteSubmission'),
    path('section/<int:section_id>/folder/assignment/upload/<int:folder_id>/<int:assignment_id>/existing', views.addExistingFilesToAssignment, name='addExistingFilesToAssignment'),
    path('section/<int:section_id>/folder/assignment/delete/<int:folder_id>/<int:assignment_id>', views.deleteFilesFromAssignment, name='deleteFilesFromAssignment'),
    path('section/<int:section_id>/folder/assignment/upload/<int:folder_id>/<int:assignment_id>/new', views.addNewFilesToAssignment, name='addNewFilesToAssignment'),
    path('reset', views.PasswordResetView, name='reset'),
    path('section/<int:section_id>/folder/assignment/submit/<int:folder_id>/<int:assignment_id>', views.submitFilesToAssignment, name='submitFilesToAssignment'),
    path('grade/view/<int:folder_id>/folder/assignment/<int:assignment_id>', views.gradesforAssignment, name='gradesforAssignment'),
    path('file/<int:file_id>', views.viewMobileContentUpload, name = "viewMobileContentUpload"),
    path('file/delete/<int:pk>/<int:section_id>/<int:folder_id>', views.delete_file, name='delete_file'),
    path('login', views.login, name='login'),
    path('grades/<int:course_id>', views.grades, name='grades'),
    path('grades', views.grades, name='grades'),
    path('students/add/<int:course_id>', views.addStudents, name='addStudents'),
    path('registration', views.registration, name='registration'),
    path('reset/<uidb64>/<token>/', views.reset, name='resetEmail'),
    path('announcements', views.announcements, name = 'announcements'),
    path('announcement/create', views.create_announcement, name='create_announcement'),
    path('attendance/<int:course_id>', views.attendance, name='attendance'),
    path('calender/view/<int:email_id>', views.calendarEventView, name='calendarEventView'),
    path('calender', views.calenderNotification, name='calenderNotification'),
    path('calender/<int:year>/<int:month>', views.calenderNotification, name='calenderNotification'),
    path('attendance/schedule/define/<int:course_id>', views.scheduleDefine, name='scheduleDefine'),
    path('attendance/upload/<int:course_id>', views.uploadAttendanceData, name='uploadAttendanceData'),
    path('attendance/photo/upload', views.uploadGroupPhoto, name='uploadGroupPhoto'),
    path('attendance/<int:course_id>/<int:year>/<int:month>/', views.attendance, name='attendance'),
    path('attendance/mark/<int:course_id>/<int:day>/<int:month>/<int:year>/', views.mark_attendance, name='mark_attendance'),
    path('profile/<int:course_id>', views.profile, name='profile'),
    path('profile', views.profile, name='profile'),
    path('profile/upload/photo/<int:course_id>', views.upload_profile_photo, name='upload_profile_photo_with_course'),
    path('profile/upload/photo', views.upload_profile_photo, name='upload_profile_photo'),
    path('carousel/school/photo/up/<int:image_id>', views.moveCarouselImageUp, name = "moveCarouselImageUp"),
    path('carousel/school/photo/down/<int:image_id>', views.moveCarouselImageDown, name = "moveCarouselImageDown"),
    path('carousel/photo/up/<int:image_id>', views.moveMainCarouselImageUp, name = "moveMainCarouselImageUp"),
    path('carousel/photo/down/<int:image_id>', views.moveMainCarouselImageDown, name = "moveMainCarouselImageDown"),
    path('carousel/school/delete', views.delete_carousel_image, name='delete_carousel_image'),
    path('carousel/delete', views.delete_main_carousel_image, name='delete_main_carousel_image'),
    path('admin/user/delete', views.delete_user, name='delete_user'),
    path('logout/', views.signout, name='logout'),
    path('contact/spam/<int:contact_id>/', views.contactSpam, name='contactSpam'),
    path('contact/delete/<int:contact_id>/', views.contactDelete, name='contactDelete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models

class ProfilePhoto(models.Model):
    file = models.FileField(upload_to="profile_photos/")
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Photo uploaded on {self.uploaded_at}"

class CustomUser(AbstractUser):
    WEB_MANAGER = 'webmanager'
    ADMIN = 'admin'
    TEACHER = 'teacher'
    STUDENT = 'student'
    PARENT = 'parent'

    USER_TYPES = [
        (WEB_MANAGER, 'Web Manager'),
        (ADMIN, 'Admin'),
        (TEACHER, 'Teacher'),
        (STUDENT, 'Student'),
        (PARENT, 'Parent'),
    ]

    profile_photo = models.FileField(upload_to='profile_photos/', blank=True, null=True)
    profile_photos = models.ManyToManyField(
        ProfilePhoto,
        related_name='users',
        blank=True
    )
    usertype = models.CharField(max_length=20, choices=USER_TYPES, blank = True)
    phone_number = models.CharField(max_length=15, blank=True, null=True, unique = False)
    birth_date = models.DateField(blank=True, null=True)
    approved = models.BooleanField(blank=False, default=False)
    embedding = models.JSONField(blank=True, null=True)
    modified_profile_photo = models.BooleanField(default=True)
    def __str__(self):
        return self.first_name +" "+ self.last_name

class CarouselImage(models.Model):
    title = models.CharField(max_length=100)
    image = models.FileField(upload_to='carousel_images/')
    order = models.PositiveIntegerField(blank=True, null=True)
    description = models.TextField()
    def __str__(self):
        return self.title

class filestoAssignment(models.Model):
    file = models.FileField(upload_to='uploads/', unique = True)
    user_id = models.IntegerField()
    assignment_id = models.IntegerField()
    Date = models.DateField(auto_now_add=True)

class Courses(models.Model):
    Title = models.CharField(max_length=20, unique=True)
    Description = models.TextField()
    Status = models.BooleanField(default=True)
    Syllabus = models.FileField(upload_to='syllabus/', blank=True)
    People = models.ManyToManyField(CustomUser, blank=True)
    def __str__(self):
        return self.Title
    
class UploadedFile(models.Model):
    file = models.FileField(upload_to='uploads/', unique = True)

class UploadedAttendance(models.Model):
    file = models.FileField(upload_to='attendance/')
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

class EmailSubscriber(models.Model):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True)
    def __str__(self):
        return self.name

class WeeklyEmail(models.Model):
    email_type = models.CharField(max_length=50)
    organizer = models.CharField(
        max_length=500,
        null=True,
        blank=True,
        help_text="Organizer information (max 500 characters)"
    )
    date_created = models.DateField(auto_now_add=True)
    date_scheduled = models.DateField(null=True, blank=True)
    date_sent = models.DateField(null=True, blank=True)
    sent = models.BooleanField(default=False)
    subject = models.CharField(max_length=255, null=True, blank=True)
    
    def __str__(self):
        return f"{self.email_type.capitalize()} Weekly Email (ID: {self.pk})"

class Assignment(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    due_date = models.DateField()
    files = models.ManyToManyField(UploadedFile, blank=True)
    def __str__(self):
        return self.title

class Announcement(models.Model):
    title = models.CharField(max_length=200)
    recipients = models.ManyToManyField(Courses, blank=False)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    sent = models.BooleanField(default=False)

class Attendance(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    day = models.PositiveIntegerField()
    month = models.PositiveIntegerField()
    year = models.PositiveIntegerField()  # Optional if you need to track the year
    status = models.CharField(max_length=10, choices=[('Present', 'Present'), ('Absent', 'Absent')])

class Folder(models.Model):
    Title = models.CharField(max_length=200)
    Course_id = models.IntegerField()
    Files = models.ManyToManyField(UploadedFile, blank=True)
    Assignments = models.ManyToManyField(Assignment, blank=True)

class Section(models.Model):
    Title = models.CharField(max_length=200)
    Course_id = models.IntegerField()
    ONum = models.IntegerField()
    Status = models.BooleanField(default=True)
    Folders = models.ManyToManyField(Folder, blank = True)

class Grade(models.Model):
    assignment_id = models.IntegerField()
    course_id = models.IntegerField()
    user_id = models.IntegerField()
    grade = models.FloatField()

class Schedule(models.Model):
    startDate = models.CharField(max_length=7)
    endDate = models.CharField(max_length=7)
    days = models.TextField()
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)

class GroupPhotoAttendance(models.Model):
    file = models.FileField(upload_to='group_photo/', unique = True)

portal/forms.py
from django import forms
from .models import UploadedFile,UploadedAttendance, filestoAssignment
from .models import Announcement, Courses, CustomUser, CarouselImage, GroupPhotoAttendance, ProfilePhoto
from django_select2.forms import Select2MultipleWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

people = CustomUser.objects.filter(usertype="Student")
class UploadedFileForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['file']

class UploadedAttendanceForm(forms.ModelForm):
    student = forms.ModelChoiceField(
        queryset=people,
    )
    class Meta:
        model = UploadedAttendance
        fields = ['file','student']
    

class CarouselImageForm(forms.ModelForm):
    class Meta:
        model = CarouselImage
        fields = ['title', 'image', 'description']

class SyllabusUploadForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = ['Syllabus']  # Only include the Syllabus field

class ProfilePhotoForm(forms.ModelForm):
    class Meta:
        model = ProfilePhoto
        fields = ['file']

class FileUploadForm(forms.ModelForm):
    class Meta:
        model = filestoAssignment
        fields = ['file']

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        assignment_id = kwargs.pop('assignment_id')
        super(FileUploadForm, self).__init__(*args, **kwargs)
        self.instance.user_id = user_id
        self.instance.assignment_id = assignment_id

class GroupPhotoUploadForm(forms.ModelForm):
    class Meta:
        model = GroupPhotoAttendance
        fields = ['file']

class AnnouncementForm(forms.ModelForm):
    recipients = forms.ModelMultipleChoiceField(
        queryset=Courses.objects.all(),
        widget=Select2MultipleWidget(attrs={'class': 'js-example-basic-multiple'}),
    )
    class Meta:
        model = Announcement
        fields = ['title', 'recipients', 'content']

templates/portal/desktop_profile.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile | Sikh Study Circle Gurmukhi School</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-icons.min.css' %}" rel="stylesheet">    
    <style nonce="{{ request.csp_nonce }}">
        body {
            font-family: 'Mukta', sans-serif;
            background-color: #f8f9fa;
        }
        .sidebar-custom {
            width: 280px;
            background-color: #343a40; /* Dark color for sidebar */
            color: #fff;
            min-height: 100vh;
            padding-top: 1rem;
        }
        .btn-primary {
            background-color: #FFC107 !important;
            border: none;
            color: #000;
            font-weight: 600;
        }
        .sidebar-custom a {
            color: #fff;
        }
        .sidebar-custom a:hover {
            color: #e0a800; /* Darker yellow on hover */
        }
        .sidebar-custom .nav-link.active {
            background-color: #FFC107; /* Yellow color for active link */
            color: #000;
        }
        .sidebar-custom .nav-link.active:hover {
            background-color: #e0a800; /* Darker yellow on hover */
            color: #000;
        }
        .sidebar-custom .logo {
            font-size: 1.5rem; /* Adjust size as needed */
            font-weight: 600;
            color: #FFC107; /* Yellow color for logo */
        }
        .content {
            flex: 1;
            padding: 20px;
        }
        .profile-container {
            background-color: #fff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .profile-photo {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            object-fit: cover;
        }
        .profile-info {
            margin-left: 20px;
        }
        .profile-info h2 {
            margin-bottom: 10px;
        }
        .profile-info button {
            margin-top: 10px;
        }
        @media (max-width: 768px) {
            .sidebar-custom {
                display: none;
            }
            .sidebar-custom.show {
                display: block;
                position: fixed;
                z-index: 1040; /* Bootstrap's fixed navbar z-index */
            }
            .content {
                margin-left: 0;
            }
            .profile-photo {
                width: 100px;
                height: 100px;
            }
        }
        .btn-secondary-custom {
            background-color: #6c757d !important;
            border: none;
            color: #fff;
            font-weight: 600;
        }        .rounded-circle .me-2{
            width: "32" !important;
            height: "32" !important;
        }

        .btn-secondary-custom:hover {
            background-color: #5a6268 !important;
        }
    </style>
</head>
<body>
    <!-- Navbar for smaller screens -->
    <nav class="navbar navbar-expand-lg navbar-custom d-lg-none">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <span class="fs-4 logo">ੴ</span> {{user.usertype}} Portal
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><i class="bi bi-list"></i></span>
            </button>
        </div>
    </nav>

    <div class="d-flex">
        <!-- Sidebar -->
        <div class="sidebar-custom collapse d-lg-block" id="sidebarMenu">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-auto me-md-auto text-white text-decoration-none">
                <span class="fs-4 logo">ੴ</span>
                <span class="ms-2">{{user.usertype}} Portal</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                {% if request.user.usertype == "Teacher" or request.user.usertype == "Student" %}
                <li class="nav-item">
                    <a href="{% url 'courses' %}" class="nav-link">
                        <i class="bi bi-book"></i> Courses
                    </a>
                </li>
                <li>
                    <a href="{% url 'announcements' %}" class="nav-link">
                        <i class="bi bi-megaphone"></i> Announcements
                    </a>
                </li>
                {% if course %}
                <li>
                    <a href="{% url 'attendance' course.id %}" class="nav-link">
                        <i class="bi bi-check2-square"></i> Attendance
                    </a>
                </li>
                <li>
                    <a href="{%url 'grades' course.id %}" class="nav-link">
                        <i class="bi bi-bar-chart"></i> Grades
                    </a>
                </li>
                {%if request.user.is_superuser and request.user.usertype == "Teacher" %}
                <li>
                    <a href="{% url 'students' course.id %}" class="nav-link">
                        <i class="bi bi-people"></i> Students
                    </a>
                </li>
                {%endif%}
                {%endif%}
                {%endif%}
                {% if request.user.usertype == "Admin" %}
                <li class="nav-item">
                    <a href="{% url 'adminViewHome' %}" class="nav-link">
                        <i class="bi bi-speedometer2"></i> Dashboard
                    </a>
                </li>
                <li>
                    <a href="{% url 'carousel_management' %}" class="nav-link">
                        <i class="bi bi-images"></i> Carousel
                    </a>
                </li>
                <li>
                    <a href="{% url 'adminUsers' %}" class="nav-link">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
                <li>
                    <a href="{% url 'adminContactView' %}" class="nav-link">
                        <i class="bi bi-telephone"></i> Contact
                    </a>
                </li>
                {%endif%}

            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" id = "profilePhoto" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <img     {% if profile_photo %}src="{{ profile_photo.file.url }}"{% endif %} 
                    width = "32" height ="32" class="rounded-circle me-2 ">
                    <strong>{{user.last_name}}, {{user.first_name}}</strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                    {% if course %}
                    <li><a class="dropdown-item" href="{% url 'profile' course.id %}">Profile</a></li>
                    {%else%}
                    <li><a class="dropdown-item" href="{% url 'profile'%}">Profile</a></li>
                    {%endif%}
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </div>
        </div>

        <!-- Content Area -->
        <div class="content flex-grow-1">
            <h1 class="mb-4">Profile</h1>
            <div class="profile-container d-flex">
                <img {% if profile_photo %}src="{{ profile_photo.file.url }}"{% endif %} alt="{{ user.first_name }} {{ user.last_name }}" class="profile-photo">
                <div class="profile-info">
                    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                    <p><strong>Email:</strong> {{ user.email }}</p>
                    <p><strong>User Type:</strong> {{ user.get_usertype_display }}</p>
                    <!-- Button to trigger modal -->
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#changeProfilePhotoModal">
                        Change Profile Photo
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for changing profile photo -->
    <div class="modal fade" id="changeProfilePhotoModal" tabindex="-1" aria-labelledby="changeProfilePhotoModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="changeProfilePhotoModalLabel">Change Profile Photo</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% if course %}
                        <form method="post" enctype="multipart/form-data" action="{% url 'upload_profile_photo_with_course' course.id %}">
                    {%else%}
                        <form method="post" enctype="multipart/form-data" action="{% url 'upload_profile_photo' %}">
                    {%endif%}
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="{%static 'js/bootstrap.bundle.min.js' %}" nonce="{{ request.csp_nonce }}"></script>
</body>
</html>